README.md, actions/jupyter.user.delete.yaml, actions/src/jupyter.py, lib/jupyter_api/api_endpoints.py, lib/jupyter_api/user_api.py, lib/structs/jupyter_last_used.py, rules/jupyter.prune_inactive.yaml, sensors/jupyter.inactive_users.yaml, sensors/src/jupyter_inactive_user_sensor.py, tests/actions/test_jupyter_actions.py, tests/lib/jupyter/test_user_api.py
Adds inactive user sensors to detect users who have never accessed their
container, or have accessed it more than a given timespan ago.
Adds an action to delete users from Jupyterhub and the surrounding tests
=> Add Jupyter inactive users sensor and handling

README.md, actions/src/jupyter.py, config.schema.yaml, stackstorm_openstack.yaml.example, tests/actions/test_jupyter_actions.py
This is part of the work moving from the K-V store into the YAML file.
Ports the Jupyter API to use pack configs instead. The next PR will add support for deleting a number of accounts based on a template name.
=> Switch to using yaml for Jupyter API Keys

pack.yaml, rules/install.from.git.branch.yaml
I did manage to crash the sensor by doing two force pushes in quick succession which did need a restart using `sudo st2ctl reload --register-sensors --register-fail-on-failure --verbose` but other than that it appears to work well and the branch can be configured as in https://github.com/StackStorm-Exchange/stackstorm-git.
=> Add rule for automating pack installs

lib/email_api/email_api.py, lib/openstack_api/openstack_query.py, lib/openstack_api/openstack_server.py, tests/lib/test_openstack_server.py
- Adds try/except to ignore an error caused by the OpenStack API attempting to fetch details of servers listed in a project when they no longer exist
- Fixes error in email.server.users
- Output "No results" instead of an error when no results are found in server.list
=> Tweaks for VM emails

actions/floating.ip.list.yaml, actions/project.create.yaml, actions/src/project_action.py, lib/openstack_api/openstack_identity.py, lib/openstack_api/openstack_query.py, lib/structs/project_details.py, tests/actions/test_project_actions.py, tests/lib/test_openstack_identity.py, tests/lib/test_openstack_query.py
Adds an `email` parameter to the project.create action and puts it in the project tags. Also allows them to be listed in floating.ip.list.
=> Add project emails

lib/openstack_api/openstack_identity.py, tests/lib/test_openstack_identity.py
The hardcoded parameter isn't required, and will fail as "default"
cannot be found.
=> Remove hard-coded domain from project creation step

.github/pull_request_template.md
This template should help both submitters and reviewers by nudging them
to the various pack standards used within
=> Add initial PR template

actions/src/hypervisor.py, lib/amphorae.py, lib/jupyter_api/user_api.py, lib/post_ticket.py, tests/lib/jupyter/test_user_api.py
Adds missing timeouts to fix `missing-timeout` pylint errors after the recent update in v2.15.0.
=> Add missing timeouts for pylint

actions/workflow.freeipa.user.delete.yaml, actions/workflows/freeipa.user.delete.yaml
Adds a workflow to delete users on a given FreeIPA server, based on the equivalent user creation workflow.
---
---
Does this PR:
=> Create workflow to delete FreeIPA users

actions/workflow.email.stale.server.users.yaml, actions/workflows/email.stale.server.users.yaml
Amends the email subject and text and renames workflow.email.old.server.users -> workflow.email.stale.server.users
The subject has changed:
"Old VMs" -> "Stale VMs"
The message has been changed from
"The following VMs are over 90 days old. Please ensure they are updated or delete them if they are no longer needed."
To
"The following VMs have not been restarted or shutdown in OpenStack for over 90 days. Please ensure they are updated or delete them if they are no longer needed."
Although the updated time recorded in OpenStack can change for all events not just restarted or shutdown David pointed out that we only want to mention restart or shutdown since this is what we would like users to do. This message also has the benefit of making it clearer that the email only relates to restarts and …
=> Reword old server email workflow

actions/project.create.yaml, actions/project.delete.yaml, actions/project.update.yaml, actions/src/project_actions.py, actions/workflow.project.create.external.yaml, actions/workflow.project.create.internal.yaml, actions/workflows/project.create.external.yaml, actions/workflows/project.create.internal.yaml, lib/openstack_api/openstack_identity.py, lib/structs/project_details.py, tests/actions/test_project_actions.py, tests/lib/test_openstack_identity.py
Adds an immutable option to project create action/workflows and ensures projects that have the flag in their tags are not deleted by project.delete. Also ensures they cannot be updated by project.update except to remove the immutable flag itself. Finally a 'delete' checkbox is added to project.delete which by default is unchecked so that the action only prints out the project it found to reduce the chances of accidental deletion.
---
---
Does this PR:
Closes #20
=> Add immutable project flag

actions/jupyter.user.create.yaml, actions/src/jupyter.py, lib/jupyter_api/get_token.py, lib/jupyter_api/user_api.py, tests/actions/test_jupyter_actions.py, tests/lib/jupyter/test_user_api.py
Adds an action and tests for creating a range of Jupyter users, based on the similar user deletion action.
Includes changes based on #45
---
---
Does this PR:
=> Add action to create Jupyter users

actions/jupyter.server.start.yaml, actions/jupyter.server.stop.yaml, actions/src/jupyter.py, lib/jupyter_api/user_api.py, tests/lib/jupyter/test_server_api.py
Adds actions to start and stop default servers for Jupyter users, and tests, similar to those for creating and deleting users.
---
---
Does this PR:
=> Jupyter start stop servers

actions/workflow.jupyter.user.cleanup.yaml, actions/workflow.jupyter.user.prepare.yaml, actions/workflows/jupyter.user.cleanup.yaml, actions/workflows/jupyter.user.prepare.yaml
Depends on #52
Adds two workflows to combine Jupyter user creation/starting servers, and user deletion/stopping servers.
---
Does this PR:
=> Create workflows for Jupyter user setup/deletion

lib/enums/cloud_domains.py, lib/openstack_query/managers/query_manager.py, lib/openstack_query/managers/server_manager.py, lib/openstack_query/query_methods.py, lib/openstack_query/runners/query_runner.py, tests/enums/test_cloud_domains.py, tests/lib/openstack_query/runners/test_query_runner.py
Added a Cloud Domain Enum for setting cloud domain for actions
Changed cloud_account typing for each method in `openstack_query` module that uses it from string to CloudDomain Enum 
---
---
Does this PR:
=> Make use of cloud domains enum

README.md, tests/structs/test_smtp_account.py
Nose is unsupported, and has broken with Python 3.11+, so switch away from this
---
---
Does this PR:
=> MAINT: Switch away from nose in struct dir

actions/workflow.project.create.internal.yaml
creating a project fails when admin or stfc user box left empty - null isn't a list so the workflow fails - change to using an empty list as default value
sorry - didn't catch this in the previous bugfix PR
---
---
Does this PR:
=> BUG: fix project create yaql type issue

requirements.txt
Adds a missing Jinja2 package, and removes the dataclasses packages which is dead since our min is now 3.8+
=> BUG: add missing Jinja2 package

.github/workflows/unit_tests.yml, lib/email_api/emailer.py, lib/email_api/template_handler.py, pytest.ini, requirements.txt, run_tests.sh, tests/lib/email_api/test_email_actions.py, tests/lib/email_api/test_emailer.py, tests/lib/email_api/test_template_handler.py
Switches the unit test framework for `lib/email_api` and associated tests. Also addresses comments from #112 
The diff is dominated by us having to un-indent the whole file whilst switching from unit test to pytest, so we can continue using parametrize
=> Switch lib email api

tests/lib/openstack_query/managers/test_query_manager.py, tests/lib/openstack_query/managers/test_user_manager.py
Ports the tests found in lib/query/manages to pytest as part of the ongoing migration
=> MAINT: Port tests in lib/query/managers to pytest

tests/lib/openstack_query/handlers/test_client_side_handler.py, tests/lib/openstack_query/handlers/test_client_side_handler_datetime.py, tests/lib/openstack_query/handlers/test_client_side_handler_generic.py, tests/lib/openstack_query/handlers/test_client_side_handler_integer.py, tests/lib/openstack_query/handlers/test_client_side_handler_string.py, tests/lib/openstack_query/handlers/test_server_side_handler.py
As part of the ongoing pytest migration, port
lib/openstack_query/handlers to use pytest
The test for `handler_base` has been removed, as there was nothing to test following an earlier PR which changed it to effectively an interface
=> MAINT: Port tests for lib/openstack_query/handlers

actions/workflows/project.create.external.yaml, actions/workflows/project.create.internal.yaml
We noticed that `create_project_internal` and `create_project_external` were both providing too much information that would lead to confusion - especially that it would output the admin `project_id` which could be confused with the actual `project_id`. 
(Almost deleted the admin project because of this :grimacing: ) - hence we removed this 
---
---
Does this PR:
=> ENH: clean workflow action outputs

lib/openstack_query/query_parser.py, tests/lib/openstack_query/test_query_parser.py
Removing the text before the key value when we group query results so that we can then use the group keys in other operations
---
---
Does this PR:
=> ENH: Remove text for keys when building unique groups

lib/openstack_query/managers/query_manager.py
Really simple fix for a type issue with DateTime Actions - previously using float for `seconds` - will default to `int` I don't think anyone will want to write a query using fractions of a second :)
This fix is required #125 to be merged first
---
---
Does this PR:
=> BUG: fix DateTime type issue

lib/openstack_query/query_blocks/query_builder.py, tests/lib/openstack_query/query_blocks/test_query_builder.py
rewrite tests to use pytest fixtures and conventions - i.e. use functions instead of test classes
=> TST: Rewrite QueryBuilder Tests

lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/query_blocks/test_query_output.py
rewrite tests to use pytest fixtures and conventions - i.e. use functions instead of test classes
=> TST: Rewrite QueryOutput Tests 

tests/enums/props/test_server_properties.py, tests/enums/props/test_user_properties.py
refactor to use pytest.mark.parametrize() and pytest.raises instead of nose tools
=> TST: Refactor Prop Enums to use pytest

lib/custom_types/openstack_query/aliases.py, lib/openstack_query/query_blocks/query_parser.py, tests/lib/openstack_query/query_blocks/test_query_parser.py
rewrite tests to use pytest fixtures and conventions - i.e. use functions instead of test classes
=> TST: Rewrite QueryParser Tests

lib/openstack_query/time_utils.py, tests/lib/openstack_query/test_time_utils.py
Rewrite tests to use pytest fixtures and conventions
Patching Datetime no longer requires using a wrapper method - hence removed get_current_time method
=> TST: Refactor TimeUtils tests to use pytest

lib/openstack_query/queries/user_query.py, lib/openstack_query/runners/user_runner.py, tests/lib/openstack_query/runners/test_user_runner.py
Fixes UserRunner not returning a list, this was seen by @meoflynn 
---
---
Does this PR:
=> Hotfix user not returning list

tests/structs/test_email_params.py, tests/structs/test_query_output_details.py, tests/structs/test_smtp_account.py
refactor struct module tests to use pytest fixtures and conventions
=> TST: Refactor struct module to use pytest

pytest.ini
Fixes the local debugger not running, as we manually added codecov to the pytest.ini file. This should have only been in the GH job, and was a temporary workaround until we got that working
---
---
Does this PR:
=> BUG: Fix local debugger not running

lib/custom_types/email_api/aliases.py
If an email address has something like an apostrophe, it will split the email address into individual characters. Email params has been updated to take email addresses as a list of addresses
---
---
Does this PR:
=> BUG: Make sure email addresses to email are provided as a list

lib/custom_types/openstack_query/aliases.py, lib/enums/query/query_presets.py, lib/openstack_query/api/query_api.py, lib/openstack_query/handlers/client_side_handler.py, lib/openstack_query/handlers/client_side_handler_generic.py, lib/openstack_query/handlers/client_side_handler_string.py, lib/openstack_query/handlers/server_side_handler.py, lib/openstack_query/managers/manager_wrapper.py, lib/openstack_query/mappings/server_mapping.py, lib/openstack_query/mappings/user_mapping.py, lib/openstack_query/query_blocks/query_builder.py, lib/openstack_query/query_blocks/query_executer.py, lib/openstack_query/runners/runner_wrapper.py, lib/openstack_query/runners/server_runner.py, lib/openstack_query/runners/user_runner.py, tests/enums/test_query_presets.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/handlers/test_client_side_handler.py, tests/lib/openstack_query/handlers/test_client_side_handler_generic.py, tests/lib/openstack_query/handlers/test_client_side_handler_string.py, tests/lib/openstack_query/handlers/test_server_side_handler.py, tests/lib/openstack_query/managers/test_manager_wrapper.py, tests/lib/openstack_query/mappings/conftest.py, tests/lib/openstack_query/mappings/test_server_mapping.py, tests/lib/openstack_query/mappings/test_user_mapping.py, tests/lib/openstack_query/query_blocks/test_query_builder.py, tests/lib/openstack_query/query_blocks/test_query_executer.py, tests/lib/openstack_query/runners/test_runner_wrapper.py
refactored builder and runner methods to allow multiple where() methods to be run. This allows you to define multiple presets to filter by.
This change also fixes ANY_IN - now using ANY_IN will run multiple server-side EQUAL_TO queries and aggregate the results - acting essentially as OR
server side and client side fiilters now accept a list instead of just one
=> ENH:  Allow multiple queries on same resource

lib/openstack_query/__init__.py, tests/lib/openstack_query/test_api_imports.py
makes the importing of query objects easier for users
=> MAINT: Allow query objects to be imported at root level

lib/openstack_query/api/query_api.py, lib/openstack_query/query_blocks/query_executer.py, lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_executer.py, tests/lib/openstack_query/query_blocks/test_query_output.py
methods which handle sorting, grouping and generating output now decoupled with actually running the query - now these things can be changed at anytime and will only be calculated at the time of output without needing to re-run the query
I.e. you can do things like:
```
q1 = ServerQuery().where(...).run(...)
print(q1.group_by(a...).select(a, b, c).to_list())
print(q1.select(d, e, f).group_by(b..).sort_by(c..).to_string())
```
This will also have the hidden caveat that calling `select` will overwrite what was selected from previous calls - which means that a single select call must be used to set properties when outputting - which seems an okay trade-off
i.e. This is not possible anymore
```
q1.select(a).select(b).to_string()
```
you must do 
```
q1.select(a, b).to_string()
```
=> MAINT: separate out executing and parsing

lib/openstack_query/handlers/client_side_handler_string.py, tests/lib/openstack_query/handlers/test_client_side_handler_string.py
fix regex client-side handler regex not working
change to use a regular string because running re.compile on a normal string doesn't work
change the test to actually test whether regex works instead of just mocking it
=> BUG: fix regex bug

lib/enums/query/props/server_properties.py
change ServerQuery property mapping for flavor-id - previous one seems to be None far too often - the new mapping is more reliable
=> BUG: change flavor id property mapping

lib/openstack_query/runners/user_runner.py
When not providing meta_param `domain_id` when running a `UserQuery` - an error occurs - this fix will set a default domain-id if no meta_param given
=> BUG: domain_id key error bug

lib/openstack_query/runners/server_runner.py, tests/lib/openstack_query/runners/test_server_runner.py
Fixed a bug where "all_tenants" isn't being converted properly from meta_param into a filter kwarg 
This meant that we couldn't find all servers from all projects and it would print out the VMs on the project attached to the clouds.yaml file over and over :/
=> BUG: Fix all_tenants not being used as filter kwargs

.github/workflows/unit_tests.yml, lib/openstack_query/README.md, lib/openstack_query/api/query_api.py, lib/openstack_query/query_blocks/query_chainer.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_chainer.py
since to_list() can output a dictionary (if results are grouped) so the method may be misleading
change to:
- to_objects() - to return openstacksdk objects
- to_props() - to return selected properties
=> MAINT: update to_list API method into to_objects, to_props

lib/openstack_query/api/query_api.py, lib/openstack_query/query_blocks/query_chainer.py, lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_chainer.py, tests/lib/openstack_query/query_blocks/test_query_output.py
Queries now don't implicitly remove duplicates. Especially when chaining.
This fixes issue with keep_previous_results not working with Many-to-One type queries.
flatten() does not remove duplicates any more
=> BUG: Duplicates are no longer removed implicitly

lib/openstack_query/query_blocks/query_chainer.py, lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/query_blocks/test_query_chainer.py, tests/lib/openstack_query/query_blocks/test_query_output.py
When going back from UserQuery to ServerQuery - we get a singleton list for each user-id we fine - each of these can match to multiple servers - i.e. a single entry shunting into many other entries - one-to-many.
This is a hacky fix where if grouped properties only contains one item - we don't delete it.
This works because:
- many-to-one relationships will contain a list with multiple items - each will be assigned to a duplicate as the output is parsed - hence deleting each one after being read is fine
- one-to-one, one-to-many relationships will contain a single list - each can be assigned to any number of outputs - hence we need to keep them around - we know it only contains one item - so not deleting it is fine
I'm happy to refactor this if it doesn't make sense to people - it's just …
=> BUG: fix one-to-many chaining bug

lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/query_blocks/test_query_output.py
parsing forwarded outputs requires deleting - therefore it needs to be mutable.
When we do the parsing we need to use a copy of the forwarded outputs to do the parsing
It's slow and horrible but it works - I'm working on a refactor of the chaining feature to make this better
=> BUG: hotfix for 'delete' forwarded outputs bug

lib/openstack_query/query_blocks/result.py, lib/openstack_query/query_blocks/results_container.py, tests/lib/openstack_query/query_blocks/test_result.py, tests/lib/openstack_query/query_blocks/test_result_container.py
This PR does adds the following - part of a larger PR - see #173 for the full picture 
**`Result` class** 
which is used to store a single query result item. 
It stores the openstack item as well as any forwarded properties.
This class is responsible for outputting the value stored as_object or as_props. 
When as_props() is selected, it will concatenate any forwarded properties stored automatically 
**`ResultContainer` class** 
which is responsible for storing multiple Result objects and returning the total output to_objects/to_props. 
It is responsible for creating and managing each Result item once a query is run
Currently neither class is being used - Query Executer will make use of  this in future - this PR is being split up so it can be reviewed quicker
=> MAINT: add Results and ResultsQuery classes

actions/email.users.with.decom.flavors.yaml, actions/src/workflow_actions.py, tests/actions/test_workflow_actions.py
adds workflow_actions.py in actions layer and tests for it - which will become our default actions layer runner
added stackstorm action which uses workflow_actions and can be used to interact with workflow/email/send_decom_flavor_email.py
=> ENH: add email users with decom flavors stackstorm action

lib/workflows/email/send_decom_flavor_email.py, tests/lib/workflows/email/test_send_decom_flavor_email.py
A few changes to decom flavor email action to fix bugs where if a server with an associated user id was not found via a UserQuery, it would be ignored. 
This is incorrect - we still want an email sent out to the address set in `override_email_address`
These changes mean that we separate out finding user info from the original query. 
For each user id we encounter in the original set of servers, we run a separate user query to get the info instead. If nothing is found, we set the email address to `override_email_address`
=> MAINT: refactor decom flavor to find servers with missing user info

actions/project.create.yaml, actions/src/project_actions.py, actions/workflow.project.create.external.yaml, actions/workflow.project.create.internal.yaml, actions/workflows/project.create.external.yaml, actions/workflows/project.create.internal.yaml, lib/openstack_api/openstack_identity.py, lib/structs/project_details.py, tests/actions/test_project_actions.py, tests/lib/test_openstack_identity.py
parent_id allows setting a projects parent domain
This can be the id of a domain or another project
=> Add parent_id for project creation actions

lib/workflows/email/send_decom_flavor_email.py, tests/lib/workflows/email/test_send_decom_flavor_email.py
currently we assume every user-query generates an email_address which is not None - handle case when it is None
=> BUG: fix when no email_address found

lib/openstack_query/query_blocks/query_builder.py, tests/lib/openstack_query/query_blocks/test_query_builder.py
I rewrote these tests so that they aren't accessing protected methods, plus I think the tests are neater
see #108
=> TST: rewriting QueryBuilder Tests

actions/src/workflow_actions.py, tests/actions/test_workflow_actions.py
A bug fix had introduced a new bug where we try to get an attribute of an attribute that doesn't exist as we removed the email submodule from email actions. 
---
---
Does this PR:
=> BUG: Remove action_module param

lib/openstack_query/api/query_api.py, lib/openstack_query/query_blocks/query_executer.py, lib/openstack_query/runners/flavor_runner.py, lib/openstack_query/runners/project_runner.py, lib/openstack_query/runners/runner_utils.py, lib/openstack_query/runners/runner_wrapper.py, lib/openstack_query/runners/server_runner.py, lib/openstack_query/runners/user_runner.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_executer.py, tests/lib/openstack_query/runners/conftest.py, tests/lib/openstack_query/runners/test_flavor_runner.py, tests/lib/openstack_query/runners/test_project_runner.py, tests/lib/openstack_query/runners/test_runner_utils.py, tests/lib/openstack_query/runners/test_runner_wrapper.py, tests/lib/openstack_query/runners/test_server_runner.py, tests/lib/openstack_query/runners/test_user_runner.py
SImplify Runner class to just be concerned with how to interact with openstacksdk. Move the other methods concerned with actually running the queries out into Executer
changes include: 
Executer has two more functions `run_with_subset` and `run_with_openstacksdk`.
`RunnerWrapper` is much simpler now
Created a `RunnerUtils` for holding static methods that are shared between different Runner classes
=> MAINT: refactor Runner and Executer 

tests/lib/openstack_query/mappings/conftest.py, tests/lib/openstack_query/mappings/test_server_mapping.py
This test wasn't testing the right mapping - likely a copy-paste error
=> BUG: fix test for server mapping

lib/openstack_query/api/query_api.py, lib/openstack_query/runners/flavor_runner.py, lib/openstack_query/runners/project_runner.py, lib/openstack_query/runners/user_runner.py
`filter_kwargs` should be a single set of server-side filters not a list of them. Changed the type accordingly.
`sort_by` should be able to take string aliases like `sort_by(('id', 'ascending'))`. Changed the type accordingly
=> BUG: fix Runner and Sort By types

email_templates/wrapper.html.j2, lib/email_api/emailer.py, requirements.txt, tests/lib/email_api/test_emailer.py
Add styling to make html emails look better. 
Styles can be defined in wrapper.html with style tags
We use css-inline to automatically convert style tags to html inline styles which is required when styling html emails
=> ENH: use email wrapper and styling

lib/openstack_query/api/query_api.py, lib/openstack_query/docs/user_docs/API.md, lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_output.py
include_group_titles configures if we should print group titles when converting to string/html
=> MAINT: add extra kwarg to style output

lib/openstack_query/query_blocks/results_container.py, tests/lib/openstack_query/query_blocks/test_result_container.py
when chaining, if the chaining results in no values found, then this error is triggered - instead we should just return nothing - as there's no values to append previous query values to. 
If this is unexpected, its up to user scripts to handle the error
=> BUG: error triggered when query returns no results

actions/workflow.project.create.external.yaml, actions/workflow.project.create.internal.yaml, actions/workflow.project.defaults.set.yaml, actions/workflows/project.create.external.yaml, actions/workflows/project.create.internal.yaml, actions/workflows/project.defaults.set.yaml
moved "shared" actions between internal and external project creation out into another workflow.
Fixed issue where we hardcoded "External" on the rbac instead of using network name
=> BUG: fix external project action network config

actions/router.create.yaml, actions/src/router_actions.py, lib/openstack_api/openstack_network.py, lib/structs/router_details.py, tests/actions/test_router_actions.py, tests/lib/test_openstack_network.py
Routers for new projects have not been created in HA Mode as the default was False. Remove the handling since there isn't really any reason not to deploy HA routers and it's a potential thing to go wrong
This removes a param from the .yaml, so we'll need to explicitly install and restart St2 to detect it
---
---
Does this PR:
=> BUG: Routers not created in HA Mode

lib/openstack_query/query_blocks/query_output.py, tests/lib/openstack_query/query_blocks/test_query_output.py
refactor methods in QueryOutput and remove need for protected-access on tests
=> MAINT: Refactor QueryOutput

lib/openstack_query/query_blocks/query_grouper.py, lib/openstack_query/query_blocks/query_parser.py, lib/openstack_query/query_blocks/query_sorter.py, tests/lib/openstack_query/query_blocks/conftest.py, tests/lib/openstack_query/query_blocks/test_query_grouper.py, tests/lib/openstack_query/query_blocks/test_query_parser.py, tests/lib/openstack_query/query_blocks/test_query_sorter.py
split up QueryParser into QueryGrouper and QuerySorter. 
simplifies QueryParser class which was growing unwieldy
Also removes need for protected-access in tests
=> MAINT: refactor QueryParser

run_tests.sh
recent changes to stackstorm testing breaks our workflow - revert to using a stable tag
=> BUG: set specific branch of stackstorm to run tests with

lib/openstack_query/query_blocks/results_container.py, tests/lib/openstack_query/query_blocks/test_result_container.py
rewrite ResultsContainer class and tests so we don't need to access protected methods for tests
=> MAINT: rewrite results container tests

lib/custom_types/openstack_query/aliases.py, lib/openstack_query/handlers/server_side_handler.py, tests/lib/openstack_query/handlers/test_server_side_handler.py, tests/lib/openstack_query/mappings/test_server_mapping.py
refactor server-side-handler tests to remove need for accessing protected methods
Also remove function to check filter function arguments - in favor of EAFP
=> TST: refactor server-side-handler test

lib/email_api/emailer.py, tests/lib/email_api/test_emailer.py
new email relay servers have self-signed certs and can't be verified 
I'm going to turn tls verification off so that we can send emails temporarily. 
Since the mail servers are internal to our network this should be a major issue
=> HOTFIX: Fix verification issue with our email server bug

actions/server.search.by.datetime.yaml, actions/server.search.by.property.yaml, actions/server.search.by.regex.yaml, lib/workflows/search_by_datetime.py, lib/workflows/search_by_property.py, lib/workflows/search_by_regex.py, tests/lib/workflows/test_search_by_datetime.py, tests/lib/workflows/test_search_by_property.py, tests/lib/workflows/test_search_by_regex.py
These actions were not updated to using the latest API - `where()` calls were passing search params through an argument called `args`
We removed this and just pass search params as extra arguments using `**kwargs`. 
I also added an extra user-defined parameter `all_projects` that was missing - this is required to explicitly tell the action to search all projects rather than just the current `admin` project
=> BUG: fix issue with server search actions

actions/workflows/project.create.internal.yaml
erroneously deleted lines to create admin/stfc roles from orquesta workflow in latest PR #223 - re-added the lines. 
This has been tested on dev and works.
We will be moving away from orquesta soon so future tests should catch issues like this!
=> BUG: internal project creation hotfix

lib/openstack_query/api/query_api.py, lib/openstack_query/query_blocks/query_chainer.py, lib/workflows/send_decom_flavor_email.py, lib/workflows/send_decom_image_email.py, tests/lib/openstack_query/api/test_query_api.py, tests/lib/openstack_query/query_blocks/test_query_chainer.py, tests/lib/workflows/test_send_decom_flavor_email.py, tests/lib/workflows/test_send_decom_image_email.py
previously append_from would work like this:
```
query.append_from("project", cloud_account="prod", "project_id", "project_name")
```
now it works like this
```
query.append_from("project", cloud_account="prod", props=["project_id", "project_name"])
```
which is more intuitive and fits python conventions
=> MAINT: update append_from function signature

lib/openstack_api/openstack_security_groups.py, lib/workflows/create_external_project.py, lib/workflows/create_internal_project.py, tests/lib/openstack_api/test_openstack_security_groups.py, tests/lib/workflows/test_create_external_project.py, tests/lib/workflows/test_create_internal_project.py
Convert create_external_project and create_internal_project into standalone python scripts - this will enable us to deprecate the orquesta workflows that we currently use
=> PROTO: project creation scripts without orquesta

lib/openstack_api/openstack_project.py, lib/workflows/project_actions.py, lib/workflows/quota_actions.py, lib/workflows/role_actions.py, tests/lib/openstack_api/test_openstack_project.py, tests/lib/workflows/test_project_actions.py, tests/lib/workflows/test_quota_actions.py, tests/lib/workflows/test_role_actions.py
This is so we can remove all the unnecessary code under actions.src.*. We're only keeping useful actions here - other ones can be easily done using openstack cli so we shouldn't re-invent the wheel
=> PROTO: moving useful actions into workflow folder

actions/email.users.with.errored.vms.yaml, email_templates/html/errored_vm.html.j2, email_templates/plaintext/errored_vm.txt.j2, lib/workflows/send_errored_vm_email.py, tests/lib/workflows/test_send_errored_vm_email.py
---
* [✔️] Added unit tests?
* [❌] Checked the latest commit runs on Dev?
* [❌] Updated the example config file(s) and README?
---
Does this PR:
=> Emailing users with errored VMs.

actions/email.ops.down.disabled.hypervisors.yaml
this action wasn't converted over to use new workflow using lib_entry_point
=> BUG: use new openstack actions workflow for email.ops action

lib/workflows/search_by_expression.py, tests/lib/workflows/test_search_by_expression.py
this workflow action allows querying generic openstack resources for numerical properties based on an expression - e.g "less-than" or "greater-than" a given threshold
Future stackstorm actions will make use of it
=> ENH: add search_by_expression workflow

actions/project.search.by.regex.yaml, stackstorm_openstack.yaml.example
- Added in `project.search.by.regex.yaml` to search projects by regex
- The only properties that you can search by are `name` and `description` as they are the only options in `mappings/project_mapping.py`
- I am unable to test this on dev as there is a pagination error that I have raised with Anish who suggested that it can be tested on prod. 
---
---
Does this PR:
=> ENH: Add project search by regex action

actions/server.search.by.datetime.yaml, actions/server.search.by.property.yaml, actions/server.search.by.regex.yaml, actions/user.search.by.property.yaml, actions/user.search.by.regex.yaml
Add null as an option for group_by, fixes error that null is not an option when no group_by is selected
Add null as an option for group_by, fixes error that null is not an option when no group_by is selected
---
Does this PR:
=> BUG: Fix actions when group_by is null

actions/hv.search.by.expression.yaml, actions/hv.search.by.regex.yaml, actions/project.search.by.property.yaml, actions/project.search.by.regex.yaml, actions/server.search.by.datetime.yaml, actions/server.search.by.property.yaml, actions/server.search.by.regex.yaml, actions/user.search.by.property.yaml, actions/user.search.by.regex.yaml, lib/workflows/search_by_datetime.py, lib/workflows/search_by_expression.py, lib/workflows/search_by_property.py, lib/workflows/search_by_regex.py, lib/workflows/to_webhook.py, tests/lib/workflows/test_search_by_datetime.py, tests/lib/workflows/test_search_by_expression.py, tests/lib/workflows/test_search_by_property.py, tests/lib/workflows/test_search_by_regex.py, tests/lib/workflows/test_to_webhook.py
Add to_webhook output which sends the results of a search action to a webhook. 
This will allow the output of a search action to send triggers for each item in the results to a webhook which will create a trigger to start other actions.
---
---
Does this PR:
=> ENH: Add webhook output to search actions

actions/server.search.by.datetime.yaml
Changed lib_entry_point default in server.search.by.datetime parameters since StackStorm earlier used to output:
```
AttributeError: module 'workflows' has no attribute 'search_by_datetime_search_by_datetime'
```  
when running the action. 
This addresses that issue. However, further issues still exist:
1. `group_by` is listed as optional but is required for the action to start running
2. Currently running anything shows `parse_meta_params() got an unexpected keyword argument 'limit_by_projects'` as an error.
So I am currently creating a draft pull request for this.
---
---
Does this PR:
=> BUG: fix lib_entry_point default for server datetime search action

actions/hv.search.by.property.yaml, actions/server.search.by.datetime.yaml, actions/server.search.by.property.yaml, actions/server.search.by.regex.yaml
add hv.search.by.property action and fix other search actions so that they work without needing to specify group-by
=> ENH: add hv search action

actions/server.search.by.datetime.yaml, actions/server.search.by.property.yaml, actions/server.search.by.regex.yaml
Remove extra line and duplicate keys from group_by enum in server actions
---
---
Does this PR:
=> BUG: Fix server actions

lib/icinga_api/downtime.py, tests/lib/icinga_api/test_downtime.py
Schedule and Remove downtime should raise http errors, e.g. 404 when host/service is not found
---
---
Does this PR:
=> MAINT: Make icinga downtime raise http errors

actions/image.search.by.datetime.yaml, actions/image.search.by.expression.yaml, actions/image.search.by.property.yaml, actions/image.search.by.regex.yaml
written by @Neonbluestoplight
---
---
Does this PR:
=> ENH: add image search actions

actions/server.search.by.datetime.yaml
`limit_by_projects` was returning:
`TypeError: parse_meta_params() got an unexpected keyword argument 'limit_by_projects'`
Changed to `from_projects`.
---
---
Does this PR:
=> BUG: Changed limit_by_projects to from_projects for server datetime search action

rules/hv.patch.reboot.yaml
Added a rule which starts the `hv.patch.reboot` action when the trigger `hypervisor_state_change` changes for a HV from "DRAINING" to "DRAINED"
---
---
Does this PR:
=> ENH: Added rule to start the patch reboot workflow

tests/lib/icinga_api/test_downtime.py, tests/sensors/test_hypervisor_state_sensor.py
- After a discussion with Anish I've changed some of the `unittest` classes to be `pytest` tests and added `pytest.fixtures` if needed. 
- There are a few changes that I am unsure of with the fixtures (specifically in `test_hypervisor_state_sensor`. 
---
---
Does this PR:
=> Changed tests to use pytest instead of unittest.

actions/project.search.by.property.yaml
Action fails to run with default values as null is not an accepted value, adding "null" to the list of Enums fixes this.
---
---
Does this PR:
=> BUG: group by does not accept default of null

actions/server.migrate.yaml, lib/openstack_api/openstack_server.py, lib/workflows/icinga_downtime.py, policies/migrate_server_policy.yaml, rules/webhook.server.migrate.yaml, tests/lib/openstack_api/test_openstack_server.py, tests/lib/workflows/test_icinga_downtime.py
- Prevents any migration of GPU (g-*) flavors, this applies to all migration actions
- Blacklist and Whitelist flavor able to be migrated through the migration webhook, these flavors can still be migrated by running the action manually
- Add a concurrency policy to limit the number of concurrent migrations running at a time
- Fix icinga downtime action
---
Does this PR:
=> ENH: Add restrictions to automatic migrations

actions/hv.search.by.property.yaml, lib/enums/hypervisor_states.py, lib/openstack_api/openstack_hypervisor.py, tests/lib/openstack_api/test_openstack_hypervisor.py
- Added in the PENDING_MAINTENANCE enum to be determined before EMPTY. 
- Added the uptime option to the `hv.search.by.property` action
---
---
Does this PR:
=> Fix HV state bug

lib/jira_api/connection.py, lib/jira_api/jira_issue.py, tests/lib/jira_api/test_connection.py, tests/lib/jira_api/test_jira_issue.py, tests/lib/jira_api/test_template_handler.py
For clarity, move the class JiraConnection to its own module. This way, it is more clear the purpose of the module jira_issue.py, just to create new tickets.
=> Move JiraConnection to a separate file

lib/openstack_api/openstack_server.py, tests/lib/openstack_api/test_openstack_server.py
- Fix bug in `build_server` action where previously the VMs built were not built on the correct hypervisors. 
---
---
Does this PR:
=> Fix bug with build_server action. 

actions/email.users.with.vms.on.hv.fault.notification.yaml, actions/email.users.with.vms.on.hv.maintenance.notification.yaml, lib/workflows/send_hv_email.py, rules/hv.maintenance.notification.yaml, tests/lib/workflows/test_send_hv_email.py
override email should default to a string
`to_webhook` needs to send all server properties to the webhook
- override email should default to a string
- `to_webhook` needs to send all server properties to the webhook
---
---
Does this PR:
=> Bug: Fix hv notification actions

sensors/hypervisor.state_change.yaml
Disable hv state sensor there should only be one instance running at a time to avoid stackstorm instances conflicting with each other
---
---
Does this PR:
=> Disable hv state sensor

actions/hv.patch.reboot.yaml, actions/hv.post.reboot.yaml, actions/src/openstack_actions.py, lib/workflows/hv_patch_and_reboot.py, lib/workflows/hv_post_reboot.py, requirements.txt, rules/hv.compute.service.disable.yaml, rules/hv.patch.reboot.yaml, rules/hv.post.reboot.yaml, stackstorm_openstack.yaml.example, tests/actions/test_openstack_actions.py, tests/lib/workflows/test_hv_patch_and_reboot.py, tests/lib/workflows/test_hv_post_reboot.py
This PR:
- Adds the `post_reboot` action to remove the scheduled downtime, removes the `alertmanager` silence and enables the hv in openstack when the hv is back up after a reboot
- Bug fix to add the `alertManager` to openstack_actions.py.
- Fix a typo in the migrate rule.
---
Note: There is another branch called `fix_tests` which fixes the failing coverage. 
---
---
Does this PR:
=> Post reboot action

lib/jira_api/jira_issue.py, tests/lib/jira_api/test_jira_issue.py
As it is going to be needed by future automations, we need to enhance the API to interact with JIRA.
Let's start by adding a function that allows us to reply to an existing JIRA Issue. The reply can be either an internal comment or a reply to the customer.
=> Add function to reply to JIRA Issues

lib/workflows/hv_post_reboot.py, tests/lib/workflows/test_hv_post_reboot.py
Set delete_on_failure to True for hypervisor post reboot action to remove error serevrs
---
---
Does this PR:
=> Update post reboot action

lib/structs/alertmanager/silence_details.py
Previous check was causing error when end time = start time which are allowed by alertmanager. Change to check for a negative duration instead
---
---
Does this PR:
=> Fix check for silence end time before start time

lib/enums/hypervisor_states.py, lib/openstack_api/openstack_hypervisor.py, lib/openstack_query_api/hypervisor_queries.py, lib/workflows/hv_patch_and_reboot.py, rules/hv.compute.service.disable.yaml, tests/lib/openstack_api/test_openstack_hypervisor.py, tests/lib/workflows/test_hv_patch_and_reboot.py
Add disabled state for any hypervisors disabled not disabled by stackstorm, this will prevent stackstorm automatically running action unintentionally
---
---
Does this PR:
=> Add disabled state for hypervisors

lib/openstack_api/openstack_server.py, tests/lib/openstack_api/test_openstack_server.py
Tested in dev-deployment
This PR adds checks in for the status of image and migration so that the actions in stackstorm will fail.
I am not sure why the code coverage is failing - I think the line is covered. 
---
---
Does this PR:
=> Fixed the migration functions to wait for status

lib/jira_api/issue_types/new_project_request.py, tests/lib/jira_api/test_new_project_request.py
When the user does not fill the boxes with some data, the attribute
getattr(answers, "<field number>").adf.content
is just an empty list. Therefore, we cannot just try to get the value of the first index
getattr(answers, "<field number>").adf.content[0]
as it does not exist.
---
---
Does this PR:
=> Deal with empty fields in the form

sensors/src/jira_issue_sensor.py, tests/sensors/test_jira_issue_sensor.py
To find JIRA Issues ready for automation, we need to check their "status" rather than their "statusCategory".
Those are 2 different things in JIRA.
For us, at least for the time being until the JIRA Workflow is finalised, the relevant one is the "status".
=> Fix bug in JIRA query

actions/hypervisor.downtime.yaml, lib/openstack_api/__init__.py, lib/openstack_api/openstack_server.py, lib/workflows/__init__.py, lib/workflows/hv_create_test_server.py, lib/workflows/hypervisor_downtime.py, policies/hypervisor.drain.concurrency.yaml, tests/lib/workflows/test_hypervisor_downtimes.py
- Add logging to hv test action
- Optional Downtime/Silence for downtime actions, prod hypervisors not in icinga
- Pause before migrating after a snapshot
- Limit number of hypervisors draining at a time to 2
---
---
Does this PR:
=> Improvements to help reinstalls

lib/openstack_api/openstack_server.py, tests/lib/openstack_api/test_openstack_server.py
Increase the timeout to 1 hour for server actions, this should allow enough time to complete snapshots and migrations
---
---
Does this PR:
=> Increase default timeouts for server actions

actions/chatops.pr_reminder.yaml, actions/src/openstack_actions.py, config.schema.yaml, docs/ACTIONS.md, docs/RULES.md, lib/workflows/chatops_pr_reminder.py, rules/chatops.pr_reminder.global.yaml, rules/chatops.pr_reminder.personal.yaml, stackstorm_openstack.yaml.example, tests/actions/test_openstack_actions.py, tests/lib/workflows/test_chatops_pr_reminder.py
Adds a sensor to trigger the ChatOps weekly reminders.
The sensor uses the [schedule](https://schedule.readthedocs.io/en/stable/) library to run events on specific days and times. When the schedule is triggered it makes a HTTP request to the ChatOps application with a token we provide in the pack config.
Adds extra variables to the pack config.
---
---
Does this PR:
=> Adding Cloud ChatOps Sensor

lib/enums/user_domains.py, lib/openstack_api/openstack_project.py, lib/structs/project_details.py, lib/workflows/create_jasmin_external_project.py, lib/workflows/icinga_downtime.py, tests/actions/test_openstack_actions.py, tests/enums/test_user_domains.py, tests/lib/openstack_api/test_openstack_project.py, tests/lib/workflows/test_create_jasmin_external_project.py
Initial workflow for creating an external project in a new domain. Updated the create_project method to include option for domain id and added new domain to user_domains
---
---
Does this PR:
=> ENH: Add initial new project workflow

requirements.txt, tests/lib/openstack_api/test_openstack_connection.py
dependencies are causing issues with pack install, this PR fixes it
- remove any presence of nose in tests in favor of pytest
- pin css-inline to a specific version
=> remove some unneeded dependencies

lib/workflows/find_empty_hypervisors.py, tests/lib/workflows/test_find_empty_hypervisors.py
`hypervisor_vcpus_used` has been renamed to `vcpus_used`
Closes #377
---
---
Does this PR:
=> BUG: Correct hypervisor query string alias

actions/email.mailing.list.with.create.capi.images.yaml, lib/apis/email_api/email_template_schemas.yaml, lib/apis/email_api/templates/html/mailing_list_capi_create_image.html.j2, lib/apis/email_api/templates/plaintext/mailing_list_capi_create_image.txt.j2, lib/workflows/send_mailing_list_capi_image_create_email.py, tests/lib/workflows/test_send_mailing_list_capi_image_create_email.py
Added an action to send created CAPI Images to the mailing list that users could use
---
---
Does this PR:
=> ENH: add capi image creation notification
