- .pylintrc
- README.md
- actions/jupyter.user.delete.yaml
- actions/src/jupyter.py
- lib/jupyter_api/api_endpoints.py
- sensors/src/jupyter_inactive_user_sensor.py
- tests/actions/test_jupyter_actions.py
Adds the endpoint for the new Jupyterhub platform. This represents the
three available endpoints currently available.
> Add endpoint for jupyterhub.stfc.ac.uk

- README.md
Adds docs to the readme to help get tooling and coding standards down as
the number of devs increases.
> Add docs to help devs on this project.

- actions/jupyter.user.delete.yaml
- actions/src/jupyter.py
- lib/jupyter_api/user_api.py
- lib/structs/jupyter_users.py
- tests/actions/test_jupyter_actions.py
- tests/lib/jupyter/test_user_api.py
Adds support to Stackstorm for deleting a range of users on a Jupyterhub
machine
> Add support for deleting ranges of users

- actions/workflows.project.create.external.yaml
- actions/workflows.project.create.internal.yaml
- actions/workflows/project.create.external.yaml
- actions/workflows/project.create.internal.yaml
Noticed I didn't add the project email to these workflows so they would likely have errored.
> Add project email to internal & external create workflows

- README.md
There's some documentation in the source code for the action but I wanted to make it easier to find. If there's anything about this action you have questions about let me know so that I can add it to the documentation.
> Add Create Tickets action documentation

- README.md
Documentation for the openstack check actions and sensors/rules as well as openstack.projects.sync
> Add documentation for openstack.check.*, openstack.*.rule and openstack.projects.sync

- actions/floating.ip.list.yaml
- actions/image.list.yaml
- actions/server.list.yaml
- actions/src/image_actions.py
- lib/openstack_api/openstack_floating_ip.py
- lib/openstack_api/openstack_image.py
- lib/openstack_api/openstack_query.py
- tests/actions/test_floating_ip_actions.py
- tests/actions/test_image_actions.py
- tests/lib/test_openstack_floating_ip.py
- tests/lib/test_openstack_image.py
> Add image list action

- actions/email.image.users.yaml
- actions/email.server.users.yaml
- actions/src/email_actions.py
- tests/actions/test_email_actions.py
- tests/lib/test_openstack_query.py
Adds the email.image.users action and does some clean-up to reduce some code repetition.
Also noticed an error when there are no emails to send, so fixed that.
> Add image emails

- actions/src/user_actions.py
- actions/user.list.yaml
- lib/openstack_api/openstack_query.py
- lib/openstack_api/openstack_user.py
- tests/actions/test_user_actions.py
- tests/lib/test_openstack_query.py
- tests/lib/test_openstack_user.py
Fixes user.list action bringing it in line with the other list actions.
---
---
Does this PR:
> Fix user.list action

- lib/jupyter_api/user_api.py
- tests/lib/jupyter/test_user_api.py
Fixes an incorrect unit test noticed by Elliot
Fixes some incorrect imports preventing nose tests running locally by removing the logger from the sensor
---
---
Does this PR:
> Fix incorrect unit test

- actions/workflow.email.errored.server.users.yaml
Fix workflow.email.errored.server.users description
---
---
Does this PR:
> Fix workflow.email.errored.server.users description

- actions/flavor.list.missing.flavors.yaml
- actions/src/flavor_actions.py
- lib/openstack_api/openstack_flavor.py
- tests/actions/test_flavor_actions.py
- tests/lib/test_openstack_flavor.py
Python script and unit test in action layer for migrating OpenStack Flavors.
---
---
Does this PR:
> Actions for migrating Flavors

- lib/openstack_query/__init__.py
- lib/openstack_query/handlers/client_side_handler.py
- lib/openstack_query/handlers/server_side_handler.py
- lib/openstack_query/managers/query_manager.py
- lib/openstack_query/managers/user_manager.py
- lib/openstack_query/query_builder.py
- lib/openstack_query/query_methods.py
- lib/openstack_query/query_output.py
- lib/openstack_query/runners/query_runner.py
- lib/openstack_query/runners/server_runner.py
- lib/openstack_query/runners/user_runner.py
- tests/lib/openstack_query/handlers/test_client_side_handler.py
- tests/lib/openstack_query/handlers/test_server_side_handler.py
- tests/lib/openstack_query/managers/test_query_manager.py
- tests/lib/openstack_query/mocks/mocked_structs.py
- tests/lib/openstack_query/runners/test_query_runner.py
- tests/lib/openstack_query/test_query_builder.py
- tests/lib/openstack_query/test_query_methods.py
- tests/lib/openstack_query/test_query_output.py
Adds logging for openstack query - as per #96 
A few minor changes to error messages and tweaks to functions
A few minor tweaks to tests so logging doesn't break them
---
---
Does this PR:
> Openstack query/add logging

- actions/server.search.by.datetime.yaml
- actions/server.search.by.property.yaml
- actions/server.search.by.regex.yaml
- actions/user.search.by.property.yaml
- actions/user.search.by.regex.yaml
- lib/custom_types/openstack_query/aliases.py
- lib/enums/query/props/user_properties.py
- lib/openstack_query/managers/query_manager.py
- lib/openstack_query/managers/server_manager.py
- lib/openstack_query/queries/query_wrapper.py
- lib/openstack_query/queries/server_query.py
- lib/openstack_query/queries/user_query.py
- lib/openstack_query/query_methods.py
- lib/openstack_query/runners/query_runner.py
- lib/openstack_query/runners/server_runner.py
- lib/openstack_query/runners/user_runner.py
- tests/lib/openstack_query/managers/test_query_manager.py
- tests/lib/openstack_query/runners/test_query_runner.py
- tests/lib/openstack_query/runners/test_server_runner.py
- tests/lib/openstack_query/runners/test_user_runner.py
Adds pagination function for queries we expect to output a lot of values (> 1000). This significantly speeds up the process
Add ability for users to specify meta params for each Runner class - these meta params will dictate how the query will be run. 
e.g:
- Every user query requires a domain_id for it to work on - this can be specified by meta_param - "from_domain"
Fixes #79 
---
---
Does this PR:
> Add Pagination Functionality

- requirements-tests.txt
- requirements.txt
- tests/lib/jupyter/test_server_api.py
- tests/lib/jupyter/test_user_api.py
Merge these two files together since it just adds complexity for first time setup to save a small amount of space on the pack
---
Does this PR:
> MAINT: Merge requirements-test into requirements

- actions/server.search.by.datetime.yaml
- actions/server.search.by.property.yaml
- actions/server.search.by.regex.yaml
- actions/user.search.by.property.yaml
- actions/user.search.by.regex.yaml
- lib/custom_types/openstack_query/aliases.py
- lib/openstack_query/managers/query_manager.py
- lib/openstack_query/queries/query_wrapper.py
- lib/openstack_query/queries/server_query.py
- lib/openstack_query/query_methods.py
- lib/openstack_query/query_output.py
- lib/openstack_query/query_parser.py
- lib/structs/query/query_output_details.py
- tests/lib/openstack_query/managers/test_query_manager.py
- tests/lib/openstack_query/mocks/mocked_structs.py
- tests/lib/openstack_query/test_query_methods.py
- tests/lib/openstack_query/test_query_output.py
- tests/lib/openstack_query/test_query_parser.py
- tests/structs/test_query_output_details.py
Adds grouping and sorting functionality - PR for #93 
---
---
Does this PR:
> ENH: Openstack query add group and sort functionality

- tests/lib/jupyter/test_server_api.py
- tests/lib/jupyter/test_user_api.py
Port the tests/lib/jupyter directory over to use Pytest as part of our ongoing transition
> MAINT: Port tests/lib/jupyter to pytest

- lib/openstack_query/query_methods.py
- lib/openstack_query/runners/query_runner.py
- tests/lib/openstack_query/runners/test_query_runner.py
Allows users to choose different environments rather than Dev or Prod.
---
---
Does this PR:
> Changed cloud_domain to be a string.

- lib/openstack_query/managers/manager_wrapper.py
- lib/openstack_query/managers/server_manager.py
- lib/openstack_query/managers/user_manager.py
- lib/openstack_query/query_blocks/query_executer.py
- lib/openstack_query/runners/runner_wrapper.py
- lib/openstack_query/runners/server_runner.py
- lib/openstack_query/runners/user_runner.py
- tests/lib/openstack_query/managers/test_manager_wrapper.py
- tests/lib/openstack_query/runners/test_runner_wrapper.py
This PR simply renames some base classes to be \<Component\>Wrapper - just to standardise on what base classes should be named. Previous name Query\<Component\> was a bit ambiguous
---
---
Does this PR:
> Renaming some base classes

- lib/custom_types/openstack_query/aliases.py
- lib/openstack_query/managers/manager_wrapper.py
- lib/openstack_query/managers/user_manager.py
- lib/structs/query/query_output_details.py
- lib/structs/query/query_preset_details.py
very simple type fixes
---
---
Does this PR:
> Openstack query/type fixes

- tests/lib/openstack_query/handlers/test_client_side_handler_datetime.py
- tests/lib/openstack_query/handlers/test_client_side_handler_generic.py
- tests/lib/openstack_query/handlers/test_client_side_handler_integer.py
Refactor certain modules to us fixtures and pytest functions instead of as classes
> TST: Refactor various client_side_handler tests

- tests/enums/test_cloud_domains.py
- tests/enums/test_query_output_types.py
- tests/enums/test_query_presets.py
- tests/enums/test_user_domains.py
refactor tests to use pytest conventions and tests
> TST: Refactor enums to use pytest

- lib/openstack_query/query_methods.py
- tests/lib/openstack_query/test_query_methods.py
refactor tests to use pytest fixtures and conventions
> TST: Refactor query_methods to use pytest

- lib/enums/query/props/flavor_properties.py
- lib/openstack_query/__init__.py
- lib/openstack_query/api/query_objects.py
- lib/openstack_query/handlers/server_side_handler.py
- lib/openstack_query/mappings/flavor_mapping.py
- lib/openstack_query/runners/flavor_runner.py
- lib/openstack_query/runners/runner_wrapper.py
- lib/openstack_query/runners/server_runner.py
- lib/openstack_query/runners/user_runner.py
- tests/enums/props/test_flavor_properties.py
- tests/lib/openstack_query/api/test_query_objects.py
- tests/lib/openstack_query/mappings/conftest.py
- tests/lib/openstack_query/mappings/test_flavor_mapping.py
- tests/lib/openstack_query/runners/test_flavor_runner.py
- tests/lib/openstack_query/runners/test_runner_wrapper.py
- tests/lib/openstack_query/runners/test_server_runner.py
- tests/lib/openstack_query/runners/test_user_runner.py
- tests/lib/openstack_query/test_api_imports.py
Draft for getting query by flavor functionality
> ENH: add flavor query

- lib/enums/query/props/project_properties.py
- lib/openstack_query/__init__.py
- lib/openstack_query/api/query_objects.py
- lib/openstack_query/mappings/project_mapping.py
- lib/openstack_query/runners/flavor_runner.py
- lib/openstack_query/runners/project_runner.py
- lib/openstack_query/runners/runner_wrapper.py
- tests/enums/props/test_project_properties.py
- tests/lib/openstack_query/api/test_query_objects.py
- tests/lib/openstack_query/mappings/conftest.py
- tests/lib/openstack_query/mappings/test_flavor_mapping.py
- tests/lib/openstack_query/mappings/test_project_mapping.py
- tests/lib/openstack_query/mappings/test_server_mapping.py
- tests/lib/openstack_query/mappings/test_user_mapping.py
- tests/lib/openstack_query/runners/test_flavor_runner.py
- tests/lib/openstack_query/runners/test_project_runner.py
- tests/lib/openstack_query/runners/test_runner_wrapper.py
- tests/lib/openstack_query/test_api_imports.py
allows querying on openstack projects
Also fix a bug with client-side filters
> ENH: add project query

- lib/enums/query/props/server_properties.py
- lib/openstack_query/mappings/server_mapping.py
- tests/enums/props/test_server_properties.py
- tests/lib/openstack_query/mappings/test_server_mapping.py
Add IP addresses to ServerProperties
> ENH: Add IP Adresses Property 

- lib/openstack_query/api/query_api.py
- lib/openstack_query/query_blocks/query_output.py
- tests/lib/openstack_query/api/test_query_api.py
- tests/lib/openstack_query/query_blocks/test_query_output.py
to_list, to_string and to_html methods are updated to allow selecting for specific groups
Also allows flattening output into a dictionary holding unique prop values
> ENH: added features to output functions

- lib/enums/query/sort_order.py
- lib/openstack_query/api/query_api.py
- lib/openstack_query/query_blocks/query_parser.py
- tests/lib/openstack_query/query_blocks/test_query_parser.py
change sort order from requiring boolean to using an enum
resolves #106
> ENH: Add sort order enum

- lib/custom_types/openstack_query/aliases.py
- lib/enums/query/query_types.py
- lib/exceptions/query_chaining_error.py
- lib/openstack_query/api/query_api.py
- lib/openstack_query/mappings/flavor_mapping.py
- lib/openstack_query/mappings/mapping_interface.py
- lib/openstack_query/mappings/project_mapping.py
- lib/openstack_query/mappings/server_mapping.py
- lib/openstack_query/mappings/user_mapping.py
- lib/openstack_query/query_blocks/query_chainer.py
- lib/openstack_query/query_blocks/query_output.py
- lib/openstack_query/query_blocks/query_parser.py
- lib/openstack_query/query_factory.py
- lib/openstack_query/runners/user_runner.py
- lib/structs/query/query_components.py
- tests/enums/test_query_types.py
- tests/lib/openstack_query/api/test_query_api.py
- tests/lib/openstack_query/mappings/test_flavor_mapping.py
- tests/lib/openstack_query/mappings/test_project_mapping.py
- tests/lib/openstack_query/mappings/test_server_mapping.py
- tests/lib/openstack_query/mappings/test_user_mapping.py
- tests/lib/openstack_query/query_blocks/test_query_chainer.py
- tests/lib/openstack_query/query_blocks/test_query_output.py
- tests/lib/openstack_query/runners/test_user_runner.py
- tests/lib/openstack_query/test_query_factory.py
Add these methods for external chaining functionality
see #158 for more info
This PR concerns itself with just external chaining functionality - split from the draft PR
> ENH: Add then() and append_from() API Methods

- lib/openstack_query/README.md
add README for query API along with how to use it
> DOC: Add Query API README.md

- email_templates/html/decom_email.html.j2
- email_templates/plaintext/decom_email.j2
- lib/email_api/email_template_schemas.yaml
- lib/workflows/email/send_decom_flavor_email.py
- tests/lib/workflows/email/test_send_decom_flavor_email.py
Uses query library to find info for VMs running on flavors to be decomissioned and send them an email using the email API
> ENH: add send decom flavor emails workflow

- actions/email.users.with.decom.flavors.yaml
- lib/workflows/email/send_decom_flavor_email.py
- tests/lib/workflows/email/test_send_decom_flavor_email.py
catch cases when flavor given is invalid + when no servers found with the flavor and output useful errors
add use_override flag to the stackstorm action
> BUG: various bugfixes on send email decom flavors

- lib/openstack_query/api/query_api.py
- lib/openstack_query/query_blocks/query_output.py
- tests/lib/openstack_query/api/test_query_api.py
- tests/lib/openstack_query/query_blocks/test_query_output.py
> Adding to_csv functions to the query library

- email_templates/html/decom_email.html.j2
- email_templates/plaintext/decom_email.j2
Updates to the decommissioning email templates to reflect the 'hard' end-of-life date for the C flavor hardware.
---
---
Does this PR:
> [MAINT] Update Decommissioning Email Templates

- actions/email.users.with.decom.flavors.yaml
- actions/email.users.with.decom.images.yaml
- email_templates/html/decom_flavor.html.j2
- email_templates/html/decom_image.html.j2
- email_templates/plaintext/decom_flavor.txt.j2
- email_templates/plaintext/decom_image.txt.j2
- lib/email_api/email_template_schemas.yaml
- lib/workflows/send_decom_flavor_email.py
- lib/workflows/send_decom_image_email.py
- tests/lib/workflows/test_send_decom_flavor_email.py
- tests/lib/workflows/test_send_decom_image_email.py
Adds the send decom image script and action
> ENH: add send decom image action

- actions/src/hypervisor.py
- lib/openstack_query/api/query_api.py
- lib/openstack_query/api/query_objects.py
- lib/openstack_query/query_blocks/query_output.py
- lib/workflows/send_decom_flavor_email.py
- pytest.ini
- requirements.txt
- tests/lib/openstack_query/api/test_query_objects.py
Fix a circular import breaking tests by dynamically importing modules. 
This needs a more concrete fix which I will create an issue for #215
> BUG: circular import breaking tests

- .github/workflows/unit_tests.yml
Bump the version of codecov whilst refreshing the token to avoid rate limiting we're running into
---
---
Does this PR:
> MAINT: Bump codecov version

- lib/custom_types/openstack_query/aliases.py
- lib/openstack_query/handlers/client_side_handler.py
- lib/openstack_query/handlers/client_side_handler_datetime.py
- lib/openstack_query/handlers/client_side_handler_generic.py
- lib/openstack_query/handlers/client_side_handler_integer.py
- lib/openstack_query/handlers/client_side_handler_string.py
- tests/lib/openstack_query/api/test_query_api.py
- tests/lib/openstack_query/handlers/test_client_side_handler.py
- tests/lib/openstack_query/handlers/test_client_side_handler_datetime.py
- tests/lib/openstack_query/handlers/test_client_side_handler_generic.py
- tests/lib/openstack_query/handlers/test_client_side_handler_integer.py
- tests/lib/openstack_query/handlers/test_client_side_handler_string.py
refactor client-side-handler tests to remove need for accessing protected methods
> TST: refactor client-side-handler tests

- lib/openstack_query/query_blocks/query_chainer.py
- lib/openstack_query/query_blocks/query_parser.py
Didn't change references for updating how grouping works
---
---
Does this PR:
> Fixed bug with query chaining and grouping

- lib/custom_types/openstack_query/aliases.py
- lib/openstack_query/api/query_api.py
- lib/openstack_query/handlers/client_side_handler.py
small changes to types to remove warnings of expected types
> MAINT: fix type issues 

- actions/security.group.rule.set.external.yaml
- actions/src/security_group_actions.py
- actions/workflows/project.create.external.yaml
- actions/workflows/project.create.internal.yaml
- actions/workflows/project.defaults.set.yaml
- lib/openstack_api/openstack_security_groups.py
- tests/actions/test_security_group_actions.py
- tests/lib/test_openstack_security_groups.py
previously applying internal security groups to external projects - added a method and altered orquesta workflow to use new method
> BUG: fix not applying external security groups

- .github/workflows/black.yml
- .github/workflows/pylint.yml
- .github/workflows/unit_tests.yml
Updated GitHub action versions as some of them are out of date.
---
---
Does this PR:
> ENH: Updated GitHub Actions Versions

- .github/dependabot.yml
> ENH: Add dependabot to this repo

- actions/hypervisor.find.empty.yaml
- lib/workflows/find_empty_hypervisors.py
- tests/lib/workflows/test_find_empty_hypervisors.py
This reduces the noise, especially when we're powering off HVs as we have spare capacity to hand so they're unused
---
---
Does this PR:
> Add additional flag to filter out uncontactable HVs

- actions/jira.create.task.yaml
- actions/src/openstack_actions.py
- config.schema.yaml
- jira_templates/hypervisor.txt.j2
- lib/enums/issue_types.py
- lib/exceptions/jira_template_error.py
- lib/jira_api/jira_issue.py
- lib/jira_api/jira_template_schemas.yaml
- lib/jira_api/template_handler.py
- lib/structs/jira/jira_account.py
- lib/structs/jira/jira_issue_details.py
- lib/structs/jira/jira_template_details.py
- lib/workflows/create_test_issue.py
- requirements.txt
- stackstorm_openstack.yaml.example
- tests/actions/test_openstack_actions.py
- tests/lib/jira_api/test_jira_issue.py
- tests/lib/jira_api/test_template_handler.py
- tests/lib/workflows/test_create_test_issue.py
- tests/structs/test_jira_account.py
- API for creating a JIRA issue in a given board
- Test workflow for creating issue
- Templating for JIRA issue descriptions
---
---
Does this PR:
> Jira integration

- actions/hv.search.by.regex.yaml
- lib/enums/query/props/hypervisor_properties.py
- Added in `hv.search.by.regex` action to search for hypervisors by a regex pattern. 
- Corrected a typo in `hypervisor_properties.py`
---
Does this PR:
> ENH: Add hv search by regex action

- actions/icinga.remove.downtime.yaml
- actions/icinga.schedule.downtime.yaml
- actions/src/openstack_actions.py
- config.schema.yaml
- lib/enums/icinga/icinga_objects.py
- lib/icinga_api/downtime.py
- lib/structs/icinga/downtime_details.py
- lib/structs/icinga/icinga_account.py
- lib/workflows/icinga_downtime.py
- stackstorm_openstack.yaml.example
- tests/lib/icinga_api/test_downtime.py
- tests/lib/workflows/test_icinga_downtime.py
- tests/structs/test_icinga_account.py
Schedule and remove downtime actions
Tests for icinga api and workflows
Get icinga account from stackstorm config + example
Schedule and remove downtime actions
Tests for icinga api and workflows
Get icinga account from stackstorm config + example
---
Does this PR:
> ENH: Add icinga downtime actions

- actions/icinga.search.by.name.yaml
- actions/icinga.search.by.state.yaml
- lib/enums/icinga/icinga_states.py
- lib/icinga_api/query_objects.py
- lib/structs/icinga/object_query.py
- lib/workflows/icinga_search.py
- tests/lib/icinga_api/test_query_objects.py
- tests/lib/workflows/test_incinga_search.py
Add actions to search by hosts/services state or name
Add search tests
---
---
Does this PR:
> ENH: Add Search Icinga Actions

- actions/email.users.with.errored.vms.yaml
- actions/hypervisor.find.empty.yaml
These actions were using the old entrypoint method and so were non-functional - update to new version
---
---
Does this PR:
> BUG: make old actions use new entrypoint method

- actions/migrate_server.yaml
- actions/server.migrate.yaml
- lib/openstack_api/openstack_server.py
- lib/workflows/migrate_server.py
- tests/lib/openstack_api/test_openstack_server.py
- tests/lib/workflows/test_migrate_server.py
Add workflow to snapshot and migrate openstack servers to a new host
---
---
Does this PR:
> ENH: Server Migration Workflow

- config.schema.yaml
- lib/enums/hypervisor_states.py
- lib/enums/query/props/hypervisor_properties.py
- lib/openstack_api/openstack_hypervisor.py
- lib/openstack_query/docs/user_docs/query_docs/HYPERVISORS.md
- lib/openstack_query_api/hypervisor_queries.py
- sensors/hypervisor.state_change.yaml
- sensors/src/hypervisor_state_sensor.py
- stackstorm_openstack.yaml.example
- tests/lib/openstack_api/test_openstack_hypervisor.py
- tests/sensors/test_hypervisor_state_sensor.py
Sensor monitors hypervisors for state changes and dispatches a trigger when a change is detected
---
Does this PR:
> ENH: Add Hypervisor state sensor

- actions/ssh.remote.command.yaml
- lib/ssh_api/exec_command.py
- lib/structs/ssh/ssh_connection_details.py
- lib/workflows/ssh_remote_command.py
- requirements.txt
- tests/lib/ssh_api/test_exec_command.py
- tests/lib/workflows/test_ssh_remote_command.py
Add action to execute a command on a host via SSH 
---
---
Does this PR:
> ENH: Add action to execute commands over SSH

- actions/email.users.with.errored.vms.yaml
- actions/hypervisor.find.empty.yaml
- docs/ADDING_ACTIONS.md
Fixes the entrypoint which hasn't been updated for a few actions, and update the docs too
---
---
Does this PR:
> BUG: Fix entrypoint for broken actions

- actions/hv.patch.reboot.yaml
- lib/workflows/hv_patch_and_reboot.py
- tests/lib/workflows/test_hv_patch_and_reboot.py
A downtime is scheduled for the selected hypervisor and then during the downtime two ssh commands are run on the hv, patch and reboot.  These will work with the stackstorm user (currently in an aquilon sandbox) to run a patch and a reboot script.  
---
---
Does this PR:
> Hypervisor Patch and Reboot workflow

- actions/server.migrate.yaml
Was missing causing errors
---
---
Does this PR:
> BUG: Added requires_openstack to server migrate action

- rules/hv.maintenance.notification.yaml
- rules/webhook.server.migrate.yaml
Created a HV maintenance email notification rule and a webhook that initiates the server migrate action depending on the HV triggers/state.
> ENH: Drain Hypervisor Rules and Triggers

- rules/hv.compute.service.disable.yaml
Rule is triggered when the state changes from RUNNING to PENDING MAINTENANCE
---
---
Does this PR:
> ENH: Add rule to disable hypervisor

- rules/hv.compute.service.disable.yaml
causing install of the pack to fail.
> BUG: issue with quotes on rule service.disable

- actions/hv.create.test.server.yaml
- actions/server.create.yaml
- lib/openstack_api/openstack_hypervisor.py
- lib/openstack_api/openstack_server.py
- lib/workflows/hv_create_test_server.py
- tests/lib/openstack_api/test_openstack_hypervisor.py
- tests/lib/openstack_api/test_openstack_server.py
- tests/lib/workflows/test_hv_create_test_server.py
- Added create a server action
- Added hypervisor test build server action, builds either a single flavor or all available flavor on a given hypervisor
---
---
Does this PR:
> Build test server

- lib/alertmanager_api/silence.py
- lib/alertmanager_api/silence_details.py
- lib/structs/alertmanager/alertmanager_account.py
- tests/lib/alertmanager_api/test_silence.py
- tests/lib/alertmanager_api/test_silence_details.py
Address tickets:
* https://stfc.atlassian.net/browse/CLDSCRM-2238
* https://stfc.atlassian.net/browse/CLDSCRM-2290
> Create alertmanager api

- tests/lib/alertmanager_api/test_silence.py
- tests/structs/test_silence_details.py
This commit does not change the functionality of the code at all. It just adds some extra content to the docstrings, with the intention of making a little bit more clear what each test does and how. That's all.
> DOC: Add documentation to the unit tests

- .github/workflows/unit_tests.yml
- config.schema.yaml
- lib/alertmanager_api/silence.py
- lib/openstack_api/openstack_hypervisor.py
- lib/openstack_api/openstack_server.py
- lib/structs/alertmanager/silence_details.py
- lib/workflows/hv_patch_and_reboot.py
- lib/workflows/hv_post_reboot.py
- policies/migrate_server_policy.yaml
- requirements.txt
- rules/hv.post.reboot.yaml
- rules/webhook.server.migrate.yaml
- tests/lib/alertmanager_api/test_silence.py
- tests/lib/openstack_api/test_openstack_hypervisor.py
- tests/lib/workflows/test_hv_patch_and_reboot.py
- tests/lib/workflows/test_hv_post_reboot.py
This includes all bug fixes that were found during testing.  I have not included changing the polling sensor or the specific hypervisor limitations that we added in. 
---
---
Does this PR:
> Bug fixes from testing

- lib/openstack_api/openstack_server.py
ENH: The failed VM error details will be printed out
---
---
Does this PR:
> Print error details of the VM

- lib/ssh_api/exec_command.py
- lib/workflows/hv_patch_and_reboot.py
- lib/workflows/ssh_remote_command.py
- requirements.txt
- tests/lib/ssh_api/test_exec_command.py
- tests/lib/workflows/test_hv_patch_and_reboot.py
Update SSH action to print the live output of remote commands
---
---
Does this PR:
> ENH: Live SSH Output

- actions/image.share.to.project.yaml
- lib/openstack_api/openstack_image.py
- tests/lib/openstack_api/test_openstack_image.py
ENH: Added an action to share an image to a project when the image and project 
---
---
Does this PR:
> Image share action

- lib/exceptions/jira.py
- lib/jira_api/jira_issue.py
- tests/lib/exceptions/test_jira.py
- tests/lib/jira_api/test_jira_issue.py
New function in jira_api directory in stackstorm pack, to change the state of a given JIRA Issue.
> Change issue status

- lib/jira_api/jira_issue.py
- tests/lib/jira_api/test_jira_issue.py
> Add search to jira api

- lib/openstack_api/openstack_server.py
- tests/lib/openstack_api/test_openstack_server.py
Prepend server snapshot images with "st2" making it easier to search for these snapshots
---
---
Does this PR:
> Prepend server snapshots with st2

- pack.yaml
Just adding me and George to the stackstorm authors! 
---
---
Does this PR:
> Added mine and George's name to the authors

- lib/jira_api/issue_types/issue_base.py
- lib/jira_api/issue_types/new_project_request.py
- requirements.txt
- tests/lib/jira_api/test_new_project_request.py
Adds a JIRA issue base class and new project issue class. These classes serialise data from the proforma forms used in the JIRA portal. That way we can access the data much more easily.
---
---
Does this PR:
> Jira new project issue class

- actions/hypervisor.downtime.yaml
- config.schema.yaml
- lib/workflows/hypervisor_downtime.py
- tests/lib/workflows/test_hypervisor_downtimes.py
New action which is specific to hypervisors, sets icinga downtimes and silences in alertmanager for all alerts related to the hypervisor
---
---
Does this PR:
> Add hypervisor downtime action

- actions/hv.search.by.expression.yaml
- actions/hv.search.by.property.yaml
- actions/hv.search.by.regex.yaml
- requirements.txt
> Bump query library version to 1.0.0

- actions/server.migrate.yaml
- lib/openstack_api/openstack_server.py
- tests/lib/openstack_api/test_openstack_server.py
Increase the snapshot and migrate action timeout since we're limited to Python read speed for snapshots
---
---
Does this PR:
> Bump snapshot and Migrate timeout

- actions/workflows/hypervisor.drain.workflow.yaml
- policies/hypervisor.drain.concurrency.yaml
- policies/migrate.server.concurrency.yaml
- policies/migrate.server.retry.yaml
Adjust the concurrency for migration and reduce retries
See each commit for further details
---
---
Does this PR:
> Tweaks to migration concurrency attempts

- requirements.txt
PR needs to stay in draft until we can test on dev (i.e. once network is up)
---
---
Does this PR:
> MAINT: Bump minor version of our openstackquery library

- LICENSE
Add GPL3.0 license - makes it so any changes/forks are kept open-source
> Create LICENSE - GPL3.0

- actions/hv.search.by.expression.yaml
- actions/hv.search.by.property.yaml
- actions/hv.search.by.regex.yaml
- actions/image.search.by.datetime.yaml
- actions/image.search.by.expression.yaml
- actions/image.search.by.property.yaml
- actions/image.search.by.regex.yaml
- actions/project.search.by.property.yaml
- actions/project.search.by.regex.yaml
- actions/server.list.yaml
- actions/server.search.by.datetime.yaml
- actions/server.search.by.property.yaml
- actions/server.search.by.regex.yaml
- actions/user.search.by.property.yaml
- actions/user.search.by.regex.yaml
- lib/workflows/list_all_openstack.py
- lib/workflows/search_by_datetime.py
- lib/workflows/search_by_expression.py
- lib/workflows/search_by_property.py
- lib/workflows/search_by_regex.py
- tests/lib/workflows/test_list_all_openstack.py
- tests/lib/workflows/test_search_by_datetime.py
- tests/lib/workflows/test_search_by_expression.py
- tests/lib/workflows/test_search_by_property.py
- tests/lib/workflows/test_search_by_regex.py
Add `to_csv` and `to_json` output types, which I previously added to the query library, to relevant actions
---
---
Does this PR:
> ENH: add `to_csv` and `to_json` query output types

- actions/email.users.with.decom.flavors.yaml
- actions/email.users.with.decom.images.yaml
- lib/apis/email_api/templates/html/decom_flavor.html.j2
- lib/apis/email_api/templates/html/decom_image.html.j2
- lib/apis/email_api/templates/plaintext/decom_flavor.txt.j2
- lib/apis/email_api/templates/plaintext/decom_image.txt.j2
- lib/workflows/send_decom_flavor_email.py
- tests/lib/workflows/test_send_decom_flavor_email.py
Both had hardcoded EOL dates in emails, add proper EOL support
> BUG: Update email template EOLs for flavor/image decom actions
